# -*- coding: utf-8 -*-
"""calss_ex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ZFbpmpQOwltWw85JFssPnRyGy9ztLW9
"""

# __new__  create obj
# __init__ initialize obj  not constructor
# UpperCamelCase
# "Magic functions" refer to functions that start with double underscores (__)

# public : all self.id
# protected: me and my children self._id
# private: only me self.__id

class Person:
  def __init__(self,id,name,last_name,age,phone,address,gender):
    self.name = name
    self.last_name = last_name
    self.age = age
    self.phone = phone
    self.address = address
    self.gender = gender
    self.__id = id
  def show_info(self):
    print("--------------------")
    print("ID: " + self.__id)
    print("Name: " + self.name + " " + self.last_name)
    print("Age: " + str(self.age))
    print("Phone: " + self.phone)
    print("Address: " + self.address)
    print("Gender: " + self.gender)
    print("--------------------")
  def get_id(self):
    return self.__id

emp1 = Person("1","Leila","Alizadeh",30,"00393510000000","Italy","F")
emp1.show_info()
print("ID: " + emp1.get_id() ) # show private

emp1.name = "Neda"
emp1.show_info()
print(type(emp1))

# del emp1.age

class Student(Person):
  def __init__(self,id, name,last_name,age,phone,address,gender,std_id):
    Person.__init__(self,id, name,last_name,age,phone,address,gender)
    super().__init__(id,name,last_name,age,phone,address,gender)
    self._std_id = std_id
  def show_info(self):
    #Person.showInfo(self) we can show __id by this
    #print("StudentId: " + self._std_id)

    print("--------------------")
    #print("ID: " + self.__id) we cannot read because it is private
    print("Name: " + self.name + " " + self.last_name)
    print("Age: " + str(self.age))
    print("Phone: " + self.phone)
    print("Address: " + self.address)
    print("Gender: " + self.gender)
    print("StudentId: " + self._std_id)
    print("--------------------")



std1 = Student("2","Leila","Alizadeh",30,"00393510000000","Italy","F","939393")
std1.show_info()
print(type(std1))