# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s4jXUtH9IrW4DhBLrMTMxTYYcEiOZ3nU
"""

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

df = pd.read_csv('/content/sales.csv')
df.columns = ["product", "company", "category", "units_sold", "revenue" ,"cost", "profit", "purchase_date",
              "customer_name", "customer_state","customer_city", "customer_zipcode", "order_id"]
df

x = df.groupby(["product"],as_index = False).sum()["product"]
y = df.groupby(["product"],as_index = False).sum()["revenue"]
plt.plot(x,y , '-b' , linewidth = 2)
plt.title("product - revenue")
plt.xlabel ('Product')
plt.ylabel('Revenue')
#plt.subplot(2,3,1) rows, columns, location
#plt.style.use("seaborn-darkgrid")
plt.xlim()
plt.ylim()
plt.grid()
#lt.legend(loc=0, labels ="x-product")
plt.figure(figsize= (20,13), dpi = 100)
plt.show()