# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_Xp4iKz1LeuV_8bZDiSo6V7anrBY8vf
"""
# To install Numpy
# pip install numpy

import numpy as np


# list
print([1,2,3])
# one dimentional array
# array([1,2,3])

#list of lists
print([[1,2,3],[4,5,6]])
# two diemntional array
# array([[1,2,3],[4,5,6]])



# 1_D array
a = np.array([1,2,3])
print(a)

# 2_D array
a = np.array([[1,2,3],[4,5,6]])
print(a)

# Creating an array filled with zeros
a = np.zeros(5)
print(a)

# Creating an array filled with ones
a = np.ones(5)
print(a)

# Creating an array of random values (shown as 2x3 matrix)
a = np.random.random((2,3))
print(a)

# Creating an array filled with given value (dimensions, value)
a = np.full(3,10)
print(a)
a = np.full((2,3),10)
print(a)

# Creating an empty array (fills with arbitrary, un-initialized values)
a = np.empty(2)
print(a)
a = np.empty((2,3))
print(a)

# Creating an array of evenly spaced values (start, stop, step)
# no include stop value
a = np.arange(1,10,1)
print(a)

# Creating an array of evenly spaced values (low, high, num-values)
# include stop value
a = np.linspace(1,10,10)
print(a)

# Creating an array of random integers (low, high, size)
a = np.random.randint(1,10,10)
print(a)

#1D array 
my_1d_array = np.arange(0,20,1)
print(my_1d_array)

print("Max" , my_1d_array.max())

print("Min", my_1d_array.min())

print("Mean", my_1d_array.mean())

print("Sum", my_1d_array.sum())

print("Std", my_1d_array.std())

a = my_1d_array + 10
print(a)

a = my_1d_array - 10
print(a)

a = my_1d_array * 10
print(a)

a = my_1d_array / 10
print(a)

a = np.square(my_1d_array)
print(a)

a = np.sqrt(my_1d_array)
print(a)

a = np.sin(my_1d_array)
print(a)

a = np.cos(my_1d_array)
print(a)

a = np.tan(my_1d_array)
print(a)

a = np.sign(my_1d_array)
print(a)

a = my_1d_array[0]
print(a)

a = my_1d_array[0:6]  # not include the last one
print(a)

a = my_1d_array[-1]
print(a)

# 2 dimentional
my_2d_array = np.random.randint(1,10,(2,3))

print(my_2d_array)

print("Max" , my_2d_array.max())

print("Max in column" , my_2d_array.max(axis = 0))

print("Max in row" , my_2d_array.max(axis = 1))

print("Min", my_2d_array.min())

print("Mean", my_2d_array.mean())

print("Sum", my_2d_array.sum())

print("Std", my_2d_array.std())

b = np.array([1,2,3])
c = np.array([4,2,6])
print("b", b)
print("c", c)

a = np.add(b,c)
print(a)

a = np.subtract(b,c)
print(a)

a = np.multiply(b,c)
print(a)

a = np.divide(b,c)
print(a)

a = np.dot(b,c)
print(a)

a = b == c
print(a)

a = np.array_equal(b,c)
print(a)