# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xTt_67faxeD7BHN1hBJSl7x9SeRmJMpw
"""

import pandas as pd

df = pd.read_csv('/files/sales.csv')
#second param
# skiprows = 5 not read the fifth first rows
# nrows = 10 just read first 10  rows
# skip_blank_rows = True
# error_bad_lines = True
# warn_bad_lines = True

#first 5 rows
a = df.head()
print(a)

#first n rows
a = df.head(2)
print(a)

# last 5 rows
a = df .tail()
print(a)

# last n rows
a = df .tail(1)
print(a)

# numpy -> ndarray
# pandas -> series(one column), dataframe (more than one column)

product = df["Product"]
print(product)

product = df.Product
print(product)

a = type(df)
print(a)

a = df.describe()
print(a)

a = df.describe().T
print(a)

a = df.info
print(a)

a = df.columns
print(a)

a = df.Product.value_counts()
print(a)

a = df.nunique()
print(a)

a = df.Product.unique()
print(a)

a = len(df.Product.unique())
print(a)

a = list(df.columns)
print(a)

a = df.Company.values
print(a)

a = df[["Product","Company"]]
print(a)

# return True or False
print(df.Company == "Pepsi")

# return dataframe
print(df[df.Company == "Pepsi"])

print(df.loc[df.Product == "Cola"])

print((df.loc[df.Product == "Cola"]["Company"]).unique())

print(df.loc[df.Product == "Cola"][["Company","Category"]])

print(df["Units Sold"].max())

print(df[df["Units Sold"] == df["Units Sold"].max()][["Product","Units Sold"]])

a = df.sample(5)
print(a)

# 50% from df
a = df.sample(frac = 0.5)
print(a)

# Include all the databases, but in a different order than before.
a = df.sample(frac = 0.5)
print(a)

a = df.Product.value_counts()[:4]
print(a)

a = df[df["Units Sold"] >= 100]["Product"]
print(a)

a = df[df["Units Sold"] >= 100].count()
print(a)

a = df[df["Units Sold"] >= 1].Revenue.mean()
print(a)

a = df[df["Revenue"] == df["Revenue"].max()]["Units Sold"].value_counts().max()
print(a)