# -*- coding: utf-8 -*-
"""Pyplot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X7mzM3kD6VdDQf-80humktdgpYbGxwAi
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0,5,1000)
plt.plot(x, np.sin(x))
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.show()

x = np.linspace(0,5,20)
plt.plot(x, np.sin(x), color='r', linestyle='--')
plt.plot(x, np.sin(x), 'bo', markersize = 3)
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.show()

x = np.random.random((2, 100))
plt.scatter(x[0], x[1])
plt.show()

x = np.random.random((2, 100))
plt.plot(x[0], x[1], linestyle='', marker='.',markersize=10)
plt.show()

x = np.random.normal(size=1000)
plt.hist(x, bins = 20, density=True, ec='black', color="#900000")
plt.show()

#multiple plots

x = np.random.normal(size=1000)
plt.hist(x, bins = 20, density=True, ec='black', color ='#800000', alpha = 0.5)
x = np.linspace(-4, 4, 1000)
y = 1.0/(2*np.pi)**0.5 * np.exp(-0.5 * x**2)
plt.plot(x, y, color=(0.0, 0.2, 0.8), linewidth=4)
plt.show()

